-- require "user.pluginconf.neorg" -- TODO: I'll try it later.
-- require "user.pluginconf.impatient" -- NOTE: Deprecated
-- require("user.pluginconf.spotifytui")
-- require("user.pluginconf.lspsaga")
-- require "user.pluginconf.neoclip"
