require("user.pluginconf.telescope")
require("user.pluginconf.treesitter")
require("user.pluginconf.dressing")
require("user.pluginconf.autopairs")
require("user.pluginconf.comment")
require("user.pluginconf.gitsigns")
require("user.pluginconf.nvim-tree")
require("user.pluginconf.bufferline")
require("user.pluginconf.lualine")
require("user.pluginconf.toggleterm")
require("user.pluginconf.project")
require("user.pluginconf.impatient")
require("user.pluginconf.indentline")
require("user.pluginconf.alpha")
require("user.pluginconf.whichkey")
require("user.pluginconf.colorizer")
require("user.pluginconf.lspsaga")
require("user.pluginconf.todocomments")
require("user.pluginconf.zenmode")
require("user.pluginconf.copilotvim")
require("user.pluginconf.presence")
require("user.pluginconf.dap")
require("user.pluginconf.illuminate")
require("user.pluginconf.lightbulb")
require("user.pluginconf.harpoon")
require("user.pluginconf.auto-session")

-- require "user.pluginconf.neorg" -- TODO: I'll try it later.
