require("user.plugins.pluginspec")

spec("user.plugins.colorschemes")

spec("user.plugins.essentials")
spec("user.plugins.lsp")
spec("user.plugins.alpha")
spec("user.plugins.autopairs")
spec("user.plugins.bufferline")
spec("user.plugins.chatgpt")
spec("user.plugins.cmp")
spec("user.plugins.cloak")
spec("user.plugins.colorizer")
spec("user.plugins.comment")
spec("user.plugins.copilot")
spec("user.plugins.auto-session")
spec("user.plugins.dap")
spec("user.plugins.dressing")
spec("user.plugins.gitsigns")
spec("user.plugins.harpoon")
spec("user.plugins.illuminate")
spec("user.plugins.jdtls")
spec("user.plugins.lightbulb")
spec("user.plugins.lspsaga")
spec("user.plugins.lualine")
spec("user.plugins.navic")
spec("user.plugins.neoclip")
spec("user.plugins.neorg")
spec("user.plugins.noice")
spec("user.plugins.notify")
spec("user.plugins.nvimtree")
spec("user.plugins.oil")
spec("user.plugins.presence")
spec("user.plugins.project")
spec("user.plugins.surround")
spec("user.plugins.telescope")
spec("user.plugins.todocomments")
spec("user.plugins.toggleterm")
spec("user.plugins.treesitter")
spec("user.plugins.whichkey")
spec("user.plugins.zenmode")

spec("user.plugins.dev")
spec("user.plugins.extras")

require("user.plugins.lazy")
